itemsモデルとusersモデルのアソシエーションの定義
YKKISKW/freemarket_sample_46c pull request #58
Opened 2019-03-25 05:55 UTC by saito-masanao

2019-03-25 05:57 UTC, saito-masanao commented
itemsモデルとusersモデル間のアソシーエションを定義しました。

2019-03-28 10:31 UTC, ghost requested changes
変更差分が非常に多いので次からはもう少し小さい単位でプルリクエストを出してください。

2019-03-28 10:31 UTC, hiroki5123 commented on app/assets/javascripts/comment.js
> +                     <img class = "", src = "http://localhost:3000/assets/ikkyu-1a82e9bbfc3f7cb61b6933f35c13a7f34e40445c8664d85e4092d65012e8f099.jpg">
ここってこれでいいんでしょうか？

2019-03-28 10:31 UTC, hiroki5123 commented on app/assets/javascripts/likes.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
使っていないのであれば削除してください

2019-03-28 10:31 UTC, hiroki5123 commented on app/assets/stylesheets/likes.scss
> +// Place all the styles related to the likes controller here.
使っていないのであれば削除してください

2019-03-28 10:31 UTC, hiroki5123 commented on app/controllers/comments_controller.rb
> +  before_action :set_item
whatに書いてありませんでしたが、これは変更差分に含まれてていいものでしょうか？

2019-03-28 10:31 UTC, hiroki5123 commented on app/helpers/likes_helper.rb
> +module LikesHelper
使っていないのであれば削除しましょう

2019-03-28 10:31 UTC, hiroki5123 commented on app/views/likes/_like.html.haml
> +  = link_to '/users/sign_in' do
prefixで

2019-03-28 10:31 UTC, hiroki5123 commented on app/views/likes/_like.html.haml
> +  - unless @item.like?(current_user)
ifの中でunless ~ elseの書き方は非常に可読性が低くなるので、if elseで書き直せる場合は書き直してください

2019-03-28 10:31 UTC, hiroki5123 commented on spec/controllers/likes_controller_spec.rb
> +require 'rails_helper'
テストファイルは別のテストの作成プルリクエストを作ると思うので、その時に変更差分に含めてください。

2019-03-28 10:38 UTC, saito-masanao commented on app/assets/javascripts/likes.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
他の使っていないcoffeeファイルも含めて削除しました。

2019-03-28 10:39 UTC, saito-masanao commented on app/assets/stylesheets/likes.scss
> +// Place all the styles related to the likes controller here.
他の使っていないcssファイルも含めて削除しました。

2019-03-28 10:49 UTC, saito-masanao commented on app/helpers/likes_helper.rb
> +module LikesHelper
他の使っていないhelperファイルも含めて削除しました。

2019-03-28 11:07 UTC, saito-masanao commented on app/views/likes/_like.html.haml
> +  = link_to '/users/sign_in' do
修正しました。

2019-03-28 11:20 UTC, saito-masanao commented on app/controllers/comments_controller.rb
> +  before_action :set_item
whatに追記しました。
gifも載せました。

2019-03-28 11:25 UTC, saito-masanao commented on app/views/likes/_like.html.haml
> +  - unless @item.like?(current_user)
修正しました。

2019-03-28 11:29 UTC, saito-masanao commented on app/controllers/comments_controller.rb
> +  before_action :set_item
whatに書き加えました。
実装画面のgifも追加しました。

2019-03-28 11:30 UTC, saito-masanao commented on spec/controllers/likes_controller_spec.rb
> +require 'rails_helper'
修正しました

2019-03-28 11:30 UTC, saito-masanao commented on app/assets/javascripts/comment.js
> +                     <img class = "", src = "http://localhost:3000/assets/ikkyu-1a82e9bbfc3f7cb61b6933f35c13a7f34e40445c8664d85e4092d65012e8f099.jpg">
whatにコメント機能について追記しました。

2019-03-28 11:31 UTC, saito-masanao commented
Trelloの１カードごとにプルリクしようとしてたので、改めます。

2019-03-28 12:01 UTC, TOMARUMARU commented on app/assets/javascripts/comment.js
> +                     <img class = "", src = "http://localhost:3000/assets/ikkyu-1a82e9bbfc3f7cb61b6933f35c13a7f34e40445c8664d85e4092d65012e8f099.jpg">
src修正しましょう。localhost:3000だとdev環境でしか動作しません

2019-03-28 12:17 UTC, saito-masanao commented on app/assets/javascripts/comment.js
> +                     <img class = "", src = "http://localhost:3000/assets/ikkyu-1a82e9bbfc3f7cb61b6933f35c13a7f34e40445c8664d85e4092d65012e8f099.jpg">
修正しました。

2019-03-28 12:19 UTC, ghost approved these changes
LGTMです

2019-03-31 09:42 UTC, merged