item_search1
YKKISKW/freemarket_sample_46c pull request #69
Opened 2019-03-31 06:22 UTC by kenta-hiraoka

追加予定の機能(現時点では未実装)
.単体テスト

2019-03-31 06:33 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +        next if keyword == "" #先頭に空白があってもその後のキーワードで検索
stripを使って、はじめの空欄は除去しましょう！

2019-03-31 07:39 UTC, kenta-hiraoka commented on app/controllers/items_controller.rb
> +        next if keyword == "" #先頭に空白があってもその後のキーワードで検索
修正しました。

2019-03-31 07:46 UTC, kuroko918 reviewed
kaminariのviewファイルの不要なコメントアウトは消しておいて下さい！

2019-03-31 07:46 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +        @items = []
eachの中に@item = []とありますが、これだと、最後のkeywordしか検索できていないようですが…

2019-03-31 08:54 UTC, kenta-hiraoka commented on app/controllers/items_controller.rb
> +        @items = []
修正しました。

2019-03-31 08:58 UTC, ghost requested changes

2019-03-31 08:58 UTC, hiroki5123 commented on .gitignore
> +
内容のない変更差分は削除しましょう

2019-03-31 08:58 UTC, hiroki5123 commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
ここって保存している商品全て取得しようとしてますか？
一定の制限はかけておいたほうがいいかと思います

2019-03-31 09:50 UTC, kenta-hiraoka commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
@items = Item.where("name LIKE(?) OR description LIKE(?)", "%#{keyword}%","%#{keyword}%").page(params[:page]).per(48)
と
@all_items = Item.order("id DESC")
のどちらの部分でしょうか？
一定の制限とはどのようなものでしょうか？

2019-03-31 09:53 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
@item_allのことですね。
基本的にコメントしてある行の事になります！

2019-03-31 09:57 UTC, kuroko918 commented on .gitignore
> +
こちら如何でしょうか？

2019-03-31 09:57 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
そもそもなのですが、@itemsの中に、52行目の右辺の値を各keyword毎に入れるのですか？

2019-03-31 09:57 UTC, kuroko918 commented
コメント致しましたので、確認お願いします！

2019-03-31 10:25 UTC, kenta-hiraoka commented on .gitignore
> +
間違えてpullしてしまい記述が入ってしまった部分なので、
git reset --hardしてこの記述をしていない部分まで戻りました。

2019-03-31 10:33 UTC, kenta-hiraoka commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
>そもそもなのですが、@Itemsの中に、52行目の右辺の値を各keyword毎に入れるのですか？

whereメソッドが配列で値を返すから50行目の@items = [　]は余計ってことですかね？
認識が違ってたらすみません。。

2019-03-31 10:38 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
@items <<  52行目の右辺 と、@itemsというarrayの中に該当のkeywordを持つitemを入れていくイメージではないかなと思ったのですが、如何ですか？
このままだと、keywordをsplitした後、一番最後のkeywordのnameを含むitemのみ、@itemsの中に入っているのですが…

2019-03-31 11:45 UTC, kenta-hiraoka commented on app/controllers/items_controller.rb
> +        @all_items = Item.order("id DESC")
@kuroko918 ご指摘いただいたイメージで間違いないです！

2019-03-31 11:48 UTC, hiroki5123 commented
pushしてください〜

2019-04-02 07:28 UTC, kenta-hiraoka commented
コンフリクト解消してました
変更部分が多くすみません

2019-04-02 07:31 UTC, TOMARUMARU approved these changes
LGTM

2019-04-02 09:42 UTC, merged